apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicio
  labels:
    app: microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice
  template:
    metadata:
      labels:
        app: microservice
    spec:
      containers:
      - name: demo
        image: marcosalarcon/springcrud:v1
        ports:
        - containerPort: 8091